dist: trusty
sudo: off
addons:
  apt:
    packages:
      - python-dev

language: go

git:
  depth: 10

branches:
  only:
    - master

env:
  global:
    - SOURCE_DIR="public"
    - DESTINATION_PATH="https://haosblob.blob.core.windows.net/public/"
    - CDN_RESOURCE_GROUP="haosblog-rg"
    - CDN_ENDPOINT_NAME="haosblog"
    - CDN_PROFILE="haos-premium-cdn"

install: 
  - go get -u -v github.com/spf13/hugo
  # https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest
  - AZ_REPO=$(lsb_release -cs)
  - echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list  
  - curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - sudo apt-get install apt-transport-https
  - sudo apt-get update && sudo apt-get install azure-cli=2.0.38-1~trusty
  # installing AzCopy=7.2.0 https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-linux?toc=%2fazure%2fstorage%2fblobs%2ftoc.json
  - sudo echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod/ trusty main" > azure.list
  - sudo cp ./azure.list /etc/apt/sources.list.d/
  - sudo apt-get update
  - sudo apt-get install azcopy=7.2.0-netcore

# Build the website
script:
  - mkdir themes
  - git clone https://github.com/digitalcraftsman/hugo-icarus-theme.git themes/hugo-icarus-theme
  - hugo
  - azcopy --source $SOURCE_DIR --destination $DESTINATION_PATH --dest-key $AZURE_STORAGE_ACCESS_KEY --recursive --quiet --set-content-type
  - az login --service-principal -u $AZURE_SERVICE_PRINCIPAL_APP_ID --password $AZURE_SERVICE_PRINCIPAL_APP_PASSWORD --tenant $AZURE_SERVICE_PRINCIPAL_TENANT
  - az cdn endpoint purge -g $CDN_RESOURCE_GROUP -n $CDN_ENDPOINT_NAME --profile-name $CDN_PROFILE --content-paths "/*"
   
after_script:
  - echo "execute after script"